 # Pipeline de Execução (Ordem Lógica):
# "CameraCalibration" -> "OpenCV" -> "Reconstruction" -> "Visualization"
execution_mode: "Reconstruction"
remote_mode: True

paths:
  # 1. Calibração (Ajustado para o plural 'calibrations' como no seu print)
  calibration_images: "data/in/images_calibrations"
  calibration_output_folder: "data/out/calibrations"

  # 2. Extração de Frames
  video_input: "data/in/videos"
  frames_output: "data/out/frames"

  # 3. Reconstrução
  colmap_input: "data/out/frames"
  colmap_output: "data/out/reconstructions"
  resources: "resources"

  # 4.
  video_input_remote: "/home/bhzinn/Vídeos/Hidamari/goku.mp4"
  frames_output_remote: "data/out/frames"
  colmap_input_remote: "data/out/frames/images"
  colmap_output_remote: "data/out/reconstructions"
  resources_remote: "resources"

parameters:
  calibration:
    checkerboard_size: [8, 6]
  acquisition:
    desired_fps: 5